version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.3.0
  react: thefrontside/react@dev:alpha

jobs:
  integration-tests:
    executor: react/default
    steps:
      - add_ssh_keys:
          fingerprints: 48:d3:42:0f:47:ff:0f:71:d0:4f:17:5b:21:05:cf:90
      # - run:
      #     name: Install jq
      #     command: sudo apt-get install -y jq
      - run:
          name: Install create-react-app
          command: yarn global add create-react-app
      - run:
          name: Download example app from GitHub
          command: curl https://github.com/thefrontside/circleci-react-orb-test/archive/master.zip | unzip
      # - react/install:
      #     checkout: false
      # - react/eslint
      # - react/stylelint
      # - react/test

workflows:
  lint-validate_publish-dev:
    jobs:
      # this `lint-pack_validate_publish-dev` workflow will run on any commit
      - orb-tools/lint

      # pack your orb YAML files to a single orb.yml
      # validate the orb.yml file to ensure it is well-formed
      - orb-tools/pack:
          requires:
            - orb-tools/lint

      # release dev version of orb, for testing & possible publishing
      # requires a CircleCI API token to be stored as CIRCLE_TOKEN (default)
      # https://circleci.com/docs/2.0/managing-api-tokens
      # store CIRCLE_TOKEN as a project env var or Contexts resource
      # if using Contexts, add your context below
      - orb-tools/publish-dev:
          orb-name: thefrontside/react
          requires:
            - orb-tools/pack

      # trigger an integration workflow to test the dev version of your orb
      # an SSH key must be stored in your orb's repository and in CircleCI
      # (add the public key as a read/write key on GitHub; add the private
      # key in CircleCI via SSH Permissions, with github.com as Hostname)
      - orb-tools/trigger-integration-workflow:
          name: trigger-integration-dev
          ssh-fingerprints: a4:a9:94:61:d8:cf:bd:b6:36:7e:c9:ea:f7:1e:49:e6
          requires:
            - orb-tools/publish-dev
          filters:
            branches:
              ignore: master

      # by default, the 1st job (above) will trigger only integration tests;
      # the 2nd job (below) may also publish a production orb version
      - orb-tools/trigger-integration-workflow:
          name: trigger-integration-master
          ssh-fingerprints: a4:a9:94:61:d8:cf:bd:b6:36:7e:c9:ea:f7:1e:49:e6
          tag: master
          requires:
            - orb-tools/publish-dev
          filters:
            branches:
              only: master

  integration-tests_prod-release:
    jobs:
      # your integration test jobs go here: essentially, run all your orb's
      # jobs and commands to ensure they behave as expected. or, run other
      # integration tests of your choosing

      # this would need to be defined in a `jobs` section (not shown here)
      - integration-tests:
          name: integration-tests-dev
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /integration-.*/

      # call jobs twice, once for workflows resulting from non-master-branch
      # commits (above); once for commits to master (below)
      - integration-tests:
          name: integration-tests-master
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-.*/

      # patch, minor, or major publishing, depending on which orb source
      # files have been modified (that logic lives in the
      # trigger-integration-workflow job's source)
      - orb-tools/dev-promote-prod:
          name: dev-promote-patch
          orb-name: thefrontside/react
          requires:
            - integration-tests-master
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-patch.*/

      - orb-tools/dev-promote-prod:
          name: dev-promote-minor
          release: minor
          orb-name: thefrontside/react
          requires:
            - integration-tests-master
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-minor.*/

      - orb-tools/dev-promote-prod:
          name: dev-promote-major
          release: major
          orb-name: thefrontside/react
          requires:
            - integration-tests-master
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-major.*/
