description: >
    Build the application in production mode.
    The built assets are stored in artifacts.

executor: default

steps:

  - attach_workspace:
      at: ~/

  - build

  - store_artifacts:
      path: ./artifacts
